#配置数据源
spring:
  datasource:
    bySearch:
      testWhileIdle: true
      validationQuery: SELECT 1
      timeBestweenEvictionRunsMillis: 3600000 #每个小时确认连接是否可用
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://localhost:3306/zhszxc?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&autoReconnect=true&failOverReadOnly=false

      username: develop
      password: 123456

      # 初始化配置
      initial-size: 10
      # 最小连接数
      min-idle: 10
      # 最大连接数
      max-active: 1500
      # 获取连接超时时间
      max-wait: 60000
      # 是否缓存preparedStatement，也就是PSCache。
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: -1
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 300000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 1800000
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: true
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true

      validation-query: select 'x'
      # 配置监控统计拦截的filters
      filter:
        stat:
          enabled: true
        wall:
          config:
            multi-statement-allow: true
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: true
        enabled: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        stat-view-servlet:
          enabled: true


  #配置 Jpa
  jpa:
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: none
  #配置 redis
  redis:
    #数据库索引
    ip: localhost
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    #连接超时时间
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 10
        # 连接池最大空闲连接数
        max-idle: 10
        # 连接池最小空闲连接数
        min-idle: 0
        # 连接池最大阻塞等待时间，负值表示没有限制
        max-wait: -1ms

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token
  # 验证码
  code-key: code-key

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true

#是否开启 swagger-ui
swagger:
  enabled: true

# 文件存储路径
file:
  path: D:\eladmin\file\
  avatar: D:\eladmin\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5
